### ISSUE TITLE
Possibility to create verification Links (Magic Link)

### ISSUE THREAD

**Issue by lgastler** [tafelhilfe/tafelhilfe.de#6]
We have the plan to create specific links for Food Banks or regions which will have the ability to verify the entered data based on the defined scope. 

## Flow

1. Create a link and set a verification key (Backend, Token)
2. Share the Link, to be used by the user
3. The Frontend will forward the Token to the Backend and verify the token

## ToDos

- [ ] Setup Backend to accept tokens to form submissions
- [ ] Update Database schema to accept token
- [ ] setup Frontend to store token on access and if available add to request+

### Optional:
- [ ] Create JWT Token for each request signed by region token to make future requests accessible
- [ ] create simple Portal to create region Tokens
